name: wetransfer
description: WeTransfer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  jiffy: ^6.3.1
  json_annotation: ^4.9.0
  simple_connection_checker: ^0.2.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/

  fonts:
    - family: Aeroport
      fonts:
        - asset: assets/fonts/aeroportlight.otf
          weight: 300
        - asset: assets/fonts/aeroportregular.otf
          weight: 400
        - asset: assets/fonts/aeroportmedium.otf
          weight: 500
        - asset: assets/fonts/aeroportbold.otf
          weight: 700
        - asset: assets/fonts/aeroportblack.otf
          weight: 900